name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # Start Flask application
      - name: Start Flask application
        run: |
          nohup python app/app.py &
          sleep 5  # Wait for the server to start

      # Run tests
      - name: Run tests
        run: pytest

      # Stop Flask application
      - name: Stop Flask application
        run: |
          pkill -f "python app/app.py"

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-simple-service:latest .

      # Run container
      - name: Run Docker container
        run: docker run -d -p 5000:5000 my-simple-service:latest
